### ISSUE TITLE
from data.Mouse2D.MP1_SVG import d_g

### ISSUE THREAD

**Issue by zy-fang** [QihuangZhang/CeLEry#1]
Hi, Qihuang

Thank you for your outstanding work on CeLEry.

I've been going through the code and paper and noticed something interesting - the import statement "from data.Mouse2D.MP1_SVG import d_g." However, I couldn't find the "data.Mouse2D.MP1_SVG" code file. Would it be possible for you to provide us with access to this file or any relevant information that could help us locate it?

Best regards,
Zhaoyu

**Comment by QihuangZhang** [comment]
Hi Zhaoyu,

This step imports a prespecified list of SVG selected by other methods and stored in the file MP1_SVG.py. You may now find it in tutorial/Mouse2D/MP1_SVG.py

Of note that this is not the essential step and can be replaced by other ways of selecting spatial variable genes.

Qihuang
