### ISSUE TITLE
module 'CeLEry' has no attribute 'drop_NaN'

### ISSUE THREAD

**Issue by 123liumeng** [QihuangZhang/CeLEry#4]
Hello! Thank you very much for this tool!
I'm following the steps in the manual to run the code, but I'm getting this problem: module 'CeLEry' has no attribute 'drop_NaN'，
![屏幕截图 2024-01-11 205411](https://github.com/QihuangZhang/CeLEry/assets/88269358/ff731657-a37f-4a97-8419-f310633e9771)

I would appreciate it if you could help me determine if I'm making a mistake.

**Comment by QihuangZhang** [comment]
This is due to the CeLEry on PyPI being under a lower version. It is updated now!
