### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by kewinds** [QihuangZhang/CeLEry#7]
Thank you so much for this resource! I was trying to apply to my own spatial dataset and ran everything successfully through cel.Fit_cord. However, when I ran cel.Predict_cord, I received the following error: 
<img width="986" alt="image" src="https://github.com/QihuangZhang/CeLEry/assets/125380389/2274242b-eb12-4386-9031-62ff7ab2c6e0">

I'm new to Scanpy so maybe an issue with the way I prepared the anndata? Thanks for looking into this!

**Comment by QihuangZhang** [comment]
Have you checked that your Test data has the exactly same dimension (number of genes) as your training data? If not, you might need to obtain the common genes for both.

**Comment by kewinds** [comment]
The suggested fix worked. Apologies, I just saw the indicated checks further into the tutorial than I had reached. Maybe consider putting those in the beginning as well? Thanks again for this package!
